# Configs for pwills.com

title: "Mitch Joseph"
name: "Mitch Joseph"
#email: 
url: "https://mitch-ml.github.io"
repository: "mitch-ml/mitch-ml.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: #"minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Mitch Joseph"
  avatar : "/assets/images/bio-pic-1.png"
  bio    : "I enjoy writing about things I'm interested in - mostly computing, math, politics and cooking."
  location: "Litchfield, CT"
  github : mitch-ml
  linkedin: mitchell-joseph-108613162
  #email  : peter@pwills.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "mitch-ml-github-io"

#analytics:
#  provider: "google"
#  google:
#    tracking_id: ""


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
